shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar
  - semver

overrides:
  shell-quote: ^1.8.4
  vite: ^8.0.16

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  sharp: true
