name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@master
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Install dependencies
        run: pnpm i
      - name: Run linter
        run: pnpm lint
